SRC_DIR=./..

LIBNAME = libhardware
FULLNAME = $(LIB_DIR)/$(LIBNAME).a

include $(SRC_DIR)/rules.mk

CFLAGS += -I./                   \
          -I$(SRC_DIR)/include   \
          -I$(SRC_DIR)/libcmsis  \
          $(HARDWARE_DEFS)





