all:
	make all -C src

clean:
	make clean -C src
	
# управление приложением
app_all:
	make app_all -C src

app_clean:
	make app_clean -C src

# управление библиотекой libcmsis
cmsis_all:
	make cmsis_all -C src

cmsis_clean:
	make cmsis_clean -C src

# управление библиотекой libhardware
hardware_all:
	make hardware_all -C src

hardware_clean:
	make hardware_clean -C src
	
